echo -e "\e[1;32mPrevajam c programe:\e[0m"
echo -e "\e[1;34m---src/world.c\e[0m"
echo -e "\e[1;34m---src/world_graphics.c\e[0m"
echo -e "\e[1;34m---src/world_test.c\e[0m"
gcc main.c src/world.c src/world_graphics.c src/world_test.c -o main -lSDL2 -pthread && echo -e "\e[1;32mUSPELO!!\e[0m" || echo -e "\e[1;32mNI USPELO!!\e[0m"